version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    volumes:
      - ./ruby-app:/app
    ports:
      - "4567:4567"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: timetable_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
